version: '3'

services:

  mongo:
    restart: unless-stopped
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
      - MONGO_INITDB_DATABASE=auth
    volumes:
      - ./database/mongo-db:/data/db
    networks:
      - nextlove-network

  # server:
  #   restart: unless-stopped
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4021:3001"
  #   environment:
  #     - NODE_ENV=production
  #     - PORT=3001 # MUST match with External port above ^
  #     - DATABASE_URI=mongo # match with mongo container_name
  #     - DATABASE_PORT=27017 # match with mongo container
  #     - MONGO_USER=<username> # match with mongo container
  #     - MONGO_PASS=<password> # match with mongo container
  #     - MONGODB_COLLECTION=dgrayCollection
  #     - REFRESH_TOKEN_SECRET=<secrethash>
  #     - ACCESS_TOKEN_SECRET=<secrethash>
  #     - FRONTEND_URL_ORIGIN=https://app.mywebsite.com
  #     - FRONTEND_URL_PORT=443 # if using SSL = 443
  #   depends_on:
  #     - mongo
  #   networks:
  #     - nextlove-network

  # nginx built inside
  nextlove-app:
    image: docker-nextjs
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 4040:80 # because nginx is inside this container too
    environment:

      - MONGO_URI=
      - MONGO_PORT=
      - MONGO_COLLECTION=
      - MONGO_USER=
      - MONGO_PASSWORD=

      # PROVIDERS
      - GITHUB_ID=
      - GITHUB_SECRET=

      - FACEBOOK_ID=
      - FACEBOOK_SECRET=
    depends_on:
      - server
    networks:
      - nextlove-network
      # add to ngnix-prox-mgmt network

networks:
  nextlove-network:
    driver: bridge

volumes:
  mongo-db:
